import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import Navbar from "@/components/navbar/navbar";
import Stories from "@/components/stories/stories";
import MainTape from "@/components/main/main-tape";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "instagram",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Navbar />
        <Stories></Stories>
        <MainTape></MainTape>
      </body>
    </html>
  );
}
